name: 
description: "This page contains Quinn Rohlf's coursework for Lewis & Clark course PSYCH-425 (Human Computer Interaction)."
markdown: redcarpet
pygments: true
permalink: /posts/:title
baseurl: /HCI
rdiscount:
  extensions: [smart]
poole:
    word_seperator: '-'
    editor: 'subl'